### ISSUE TITLE
Magento2 only

### ISSUE THREAD

**Issue by tomhoad** [joshuaswarren/magescotch#11]
Is there a way to specify Magento2 only? It's unlikely anyone would need 1 and 2 side by side within the same directory.

**Comment by joshuaswarren** [comment]
They're not within the same directory; there's 2 separate installs, one for Magento 1 and one for Magento 2.

I'm already supporting two different PHP versions (PHP 5 and PHP 7) in two different boxes (joshuaswarren/magescotch and joshuaswarren/magescotch5). I thought about also breaking out one box for M1 and one for M2, but then I'd have 4 boxes to support, and I know I don't have the time to do that properly.

In the meantime, if you'd like, you can rm -rf public/magento1 and then you'll only have Magento 2 on the box.
