### ISSUE TITLE
Errors when running vagrant up

### ISSUE THREAD

**Issue by hiramhibbard** [joshuaswarren/magescotch#12]
Running vagrant up for the first time, I get SSH and permissions errors at the end:

==> default: stdin: is not a tty
==> default: cp:
==> default: cannot create regular file ‘/var/www/public/magento1/.modman/Inchoo_PHP7/.git/objects/pack/pack-707fddd7400c4d31540cd9d8bd15ca0e90e7f68e.idx’
==> default: : Permission denied
==> default: cp:
==> default: cannot create regular file ‘/var/www/public/magento1/.modman/Inchoo_PHP7/.git/objects/pack/pack-707fddd7400c4d31540cd9d8bd15ca0e90e7f68e.pack’
==> default: : Permission denied
==> default: cp: cannot create regular file ‘/var/www/public/magento2/.git/objects/pack/pack-5df445b613842a2b586e28207f02a9c869660f86.pack’: Permission denied
==> default: cp: cannot create regular file ‘/var/www/public/magento2/.git/objects/pack/pack-5df445b613842a2b586e28207f02a9c869660f86.idx’: Permission denied
==> default: cp: cannot create regular file ‘/var/www/public/magento2/app/code/Magento/Customer/view/frontend/templates/newcustomer.phtml’: Permission denied
==> default: cp: cannot create directory ‘/var/www/public/magento2/var/composer_home’: File exists
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I'm on Mac OS X 10.11.5  if that helps. Thanks!

**Comment by joshuaswarren** [comment]
The SSH error is just referring to the permission errors earlier in the output.

As far as the permission errors go - I'm trying to reproduce them locally. In that step, Vagrant is copying the files from the base box to the shared directory. Is it possible you're running magescotch in a location where your user doesn't have permission to create new files? 

If you don't mind, try this on the terminal on your Mac:

cd <directory magescotch is checked out in>
ls -l public/magento2/.git/objects/pack/
touch public/magento2/.git/objects/pack/pack-5df445b613842a2b586e28207f02a9c869660f86.idx

Then post the output here and I'll take a look.

**Comment by joshuaswarren** [comment]
Interesting - I just testing and I get a different set of errors. I don't receive permission errors, but I do get "file exists" errors. The files that already exist have bad permissions and are 0 bytes, i.e.:

----------   1 joshuawarren  staff      0 Jul  8 13:06 Quote.php

Please run through the steps I listed above when you have a chance so I can add your results to mine and try to determine what in the latest update is causing this. Thanks!

**Comment by nobuttsalex** [comment]
I'm having the same problem with a different vagrant project, did either of you find a solution to this problem? I'm also running OS X (10.11.6)

**Comment by joshuaswarren** [comment]
I can no longer reproduce this in the latest version of MageScotch, so I'm closing. Please feel free to reopen if it occurs again.
