### ISSUE TITLE
Magento is missing

### ISSUE THREAD

**Issue by jacobmc** [joshuaswarren/magescotch#13]
It seems like there should be magento files in public/magento and public/magento2. It also seems like there are no directories inside of public. It looks as if all of those files were deleted in a recent commit, from what I can tell, but I'm no vagrant expert. Would love to use this once it's working properly.

**Comment by joshuaswarren** [comment]
Those files were deleted because they're now hosted in the basebox. When you first run 'vagrant up', they're copied from the base box to those locations. 

Have you run 'vagrant up' yet? If you did and it produced and error, please post that error here and I'll take a look.

**Comment by jacobmc** [comment]
Oh ok, that makes sense. Apparently I didn't think to change the address on a second box I was running and it corrupted both, which is the cause of the errors I was getting. Sorry for the confusion, I'm still a little green when it comes to using vagrant.
