### ISSUE TITLE
No Magento Installation?

### ISSUE THREAD

**Issue by kitecom** [joshuaswarren/magescotch#23]
Just run through the instructions twice - both instances completed without error, bit the public directory only contains 
benchmark.php, 
index.php and 
test.php... 
I was rather expecting two Mage installations to be available...?
Vagrant 1.8.7
VB 5.1.6

D:\dev\mage>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'creatuity/MageScotchBox' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: Windows account.
    default:
    default: Username: *******
    default: Password (will be hidden):
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.6 running --- OK.
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> default: [vagrant-hostsupdater]   192.168.33.10  magescotch  # VAGRANT: 028bbbd7740a6b02f6c5090d0709e6fe (default) / d2ba3c69-e0d2-4f01-80e2-2a8cb0ae00a1
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting SMB shared folders...
    default: D:/dev/mage => /var/www
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.

D:\dev\mage>

**Comment by kitecom** [comment]
Please ignore previous post - third time round it appears to have worked...

**Comment by joshuaswarren** [comment]
Interesting - I'm glad you got it working. I actually just pushed support for SMB yesterday, which I'm hoping resolves several issues I've been seeing under Windows. Let me know how it works for you, as I want to make sure it works really well under Windows and not just Mac and Linux.

**Comment by kitecom** [comment]
Hi Joshua
Thanks for the response - I may have spoken too soon... I saw the Mage directories created and assumed that the previous efforst had been a glitch of some kind. Went back to the build to find a symlink/permissions error. 
Will clean out what I've done and give it another go - will keep you posted

**Comment by kitecom** [comment]
Hi Joshua

Just an FYI, I've removed and restarted this process a few times in the last couple of hours and there seems to be a different error each time (or no error but no "clean" install).
I'll keep plugging on because I think this might be one of the best bits of mag dev kit I've come across in a ling time...!
D
A couple of examples below:

1. "mesg: ttyname failed: Inappropriate ioctl for device"
2. "cp: 
==> default: cannot create symbolic link '/var/www/public/magento2/vendor/bin/***'
==> default: : Operation not supported"

**Comment by kitecom** [comment]
Hi again Joshua,
This morning's effort seems to be reasonable with the exception of the creation of symlinks... (see below). Where I've added ***HANGS*** the setup stops and waits for approx 5 - 30mins, then sometimes attempts to complete, sometimes doesn't...

D:\VMs\mage>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'creatuity/MageScotchBox'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'creatuity/MageScotchBox' is up to date...
==> default: Setting the name of the VM: mage_default_1480073080690_89277
==> default: Preparing SMB shared folders...
    default: You will be asked for the username and password to use for the SMB
    default: folders shortly. Please use the proper username/password of your
    default: Windows account.
    default:
    default: Username: david
    default: Password (will be hidden):
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
[default] GuestAdditions 5.1.10 running --- OK.
==> default: Checking for guest additions in VM...
==> default: [vagrant-hostsupdater] Checking for host entries
==> default: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> default: [vagrant-hostsupdater]   192.168.33.10  magescotch  # VAGRANT: 615a78e44043bea90e903f6d1adcec2e (default) / 3ec160d3-11c0-434a-9016-7a59bcb17b0b
==> default: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting SMB shared folders...
    default: D:/VMs/mage => /var/www
==> default: Running provisioner: fix-no-tty (shell)...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: C:/Users/David/AppData/Local/Temp/vagrant-shell20161125-2880-12e9rnx.sh
==> default: cp: cannot create symbolic link '/var/www/public/magento1/app/etc/modules/Inchoo_PHP7.xml': Operation not supported
==> default: cp: cannot create symbolic link '/var/www/public/magento1/app/code/local/Inchoo/PHP7': Operation not supported
==> default: cp: cannot create symbolic link '/var/www/public/magento1/app/code/local/Mage/Connect/Packager.php': Operation not supported
==> default: cp: cannot create symbolic link '/var/www/public/magento1/app/code/local/Mage/Core/Model/Resource/Session.php': Operation not supported
==> default: cp:
==> default: cannot create symbolic link '/var/www/public/magento2/dev/tests/functional/tests/app/Magento/BundleSampleData'
==> default: : Operation not supported
==> default: cp:
==> default: cannot create symbolic link '/var/www/public/magento2/dev/tests/functional/tests/app/Magento/CatalogSampleData'
==> default: : Operation not supported
==> default: cp:
==> default: cannot create symbolic link '/var/www/public/magento2/dev/tests/functional/tests/app/Magento/ConfigurableSampleData'
==> default: : Operation not supported
==> default: cp:
==> default: cannot create symbolic link '/var/www/public/magento2/dev/tests/functional/tests/app/Magento/CustomerSampleData'
==> default: : Operation not supported
==> default: cp:
==> default: cannot create symbolic link '/var/www/public/magento2/dev/tests/functional/tests/app/Magento/DownloadableSampleData'
==> default: : Operation not supported
==> default: cp:
==> default: cannot create symbolic link '/var/www/public/magento2/dev/tests/functional/tests/app/Magento/GroupedProductSampleData'
==> default: : Operation not supported
==> default: cp:
==> default: cannot create symbolic link '/var/www/public/magento2/dev/tests/functional/tests/app/Magento/SalesSampleData'
==> default: : Operation not supported
***HANGS***
==> default: mkdir:
==> default: cannot create directory ‘.modman’
==> default: : File exists
==> default: Could not create .modman directory
==> default: A module named 'Inchoo_PHP7' has already been checked out.
==> default: Repairing links, do not interrupt.
==> default: ln:
==> default: failed to create symbolic link '/var/www/public/magento1/app/code/local/Inchoo/PHP7'
==> default: : Operation not supported
==> default: ERROR: Unable to create symlink (/var/www/public/magento1/app/code/local/Inchoo/PHP7):
==> default:  app/code/local/Inchoo/PHP7 app/code/local/Inchoo/PHP7
==> default: It's not recommended to run n98-magerun as root user
==> default: Cache cleared
==> default: It's not recommended to run n98-magerun as root user
==> default: done

D:\VMs\mage>

**Comment by joshuaswarren** [comment]
Symlinks on a Windows-based host are very, very challenging apparently. That "Operation not supported" error is basically something that happens any time you try to create a symlink on a VirtualBox VM running on a Windows host. That's one of the reasons I recently switched the file shares over to SMB, as SMB is supposed to work around that issue. 

I'm going to do some troubleshooting later today hopefully using my Windows computer at home to see if I can get to the bottom of this.
