### ISSUE TITLE
Can't access magento2/admin_dev/

### ISSUE THREAD

**Issue by matthewwilson** [joshuaswarren/magescotch#25]
After a fresh vagrant up I cannot access http://192.168.33.10/magento2/admin_dev/

Getting a 404 Not Found

**Comment by joshuaswarren** [comment]
I'm not able to reproduce this on the current version of MageScotch. Is it possible you're running on a Windows host machine? If so, there are some known issues with Windows hosts due to the way that Vagrant on Windows handles the filesystem.

**Comment by matthewwilson** [comment]
I'm on Mac OS.

**Comment by joshuaswarren** [comment]
Odd. Does http://192.168.33.10/magento2/ pull up the demo store homepage? What about http://192.168.33.10/index.php - does that display?

**Comment by invertedfjord** [comment]
I am having the same issue where both admin urls produce a 404 for Magento one and 2. Everything else works fine.

**Comment by invertedfjord** [comment]
I was able to get it to work by using ssh and changing the url. by default it is adminpanel. Then I had to manually create an admin user as well.

**Comment by matthewwilson** [comment]
I was able to resolve the issue by deleting and reinstalling the box
