### ISSUE TITLE
Permissions issue with `/var/www/public`

### ISSUE THREAD

**Issue by carsonreinke** [joshuaswarren/magescotch#31]
The folder(s) say it is owned by `1046 dialout`, non-existent user #1046 and group `dialout` (exactly what it sounds like, for using the old fashion modem).

The problem is, PHP sessions will fail with error `session_start(): Session data file is not created by your uid`.

Permissions on these folders should be set to `www-data:www-data`.

**Comment by carsonreinke** [comment]
Oh https://github.com/joshuaswarren/magescotch/blob/master/Vagrantfile#L29, did not realize this was NFS.

**Comment by carsonreinke** [comment]
Looks like this is related to this https://github.com/hashicorp/vagrant/issues/8061

**Comment by joshuaswarren** [comment]
Looking at the upstream issue - https://github.com/hashicorp/vagrant/issues/8061 - this is a macOS-specific issue that has been resolved in newer versions of macOS that updating should resolve. If you're not using macOS or if you update to a newer version of macOS and it still doesn't work, please reopen.
