### ISSUE TITLE
Unable to upgrade Magento 2 using System Upgrade

### ISSUE THREAD

**Issue by hamdrew** [joshuaswarren/magescotch#5]
If you try to upgrade Magento 2 using the [recommended method](http://devdocs.magento.com/guides/v2.0/comp-mgr/upgrader/upgrade-start.html), you get an error:

![screenshot-192 168 33 10 2016-02-26 10-32-23](https://cloud.githubusercontent.com/assets/4921666/13358408/c6cdfeb6-dc74-11e5-917c-34f8f5fa50bf.png)

I also notice the version being displayed is _1.0.0-beta_. Was Magento 2 installed the "contributor" way using Git instead of from an archive or Composer?

**Comment by joshuaswarren** [comment]
So, MageScotch was built while I was assisting the awesome Magento DevDocs team with the M2 documentation. So those other installation paths weren't yet documented, and this copy of M2 in MageScotch was based on the developer beta, installed in a very different manner. 

I'm planning on completely replacing M2 in MageScotch very soon. Basically, my current plan of attack is:
1. Improve how the base image is built to make it easier to update and maintain and to accept PRs
2. Update from Scotch Box 2.0 to 2.5 as the underlying box
3. Resolve the other open issues
4. Rip out M1 and M2 both and replace with the latest versions

I'll keep you posted via the Issues here on Github with my progress and opportunities to contribute/assist.

**Comment by hamdrew** [comment]
Thank you for your efforts in this. I am going to play around a bit in parallel for my own education.

Please know that reporting these issues does not reflect poorly on the project, I hope you find them helpful. I and my team are really grateful you put this together. There is not a "defacto" local development solution for Magento out there, so this is a great opportunity to provide one for the community.

**Comment by joshuaswarren** [comment]
No worries, I completely understand - I do find the issues you're opening helpful and I hope you'll keep at it. 

FYI, I've decided to no longer base the Vagrant box on ScotchBox. This is going to be a painful change for me in the short-term, but it's going to make the project much easier to support in the long-run, and it's what will make it easier to accept PRs for the base box itself. You can follow along with me (slow, but steady) progress at https://github.com/joshuaswarren/magemalt

**Comment by joshuaswarren** [comment]
FYI, from what I'm reading, there's not going to be a simple workaround for this. The only way to be able to upgrade from the web interface right now is by not following some security best practices when setting up the Magento installation. 

I'd like to have you re-test once I get the next version of MageScotch released in the next day or so, but I wanted to prepare you for that possibility.

FYI, I'm presenting about MageScotch at the Magento Imagine conference next week, so there will be some new faces here on Github posting issues, as well as a flurry of updates this weekend before I present it.

**Comment by joshuaswarren** [comment]
So, because of some policy decisions at Magento + the way the updater currently works, most likely the web updater isn't going to work "out of the box". Magento 2 is being installed via the contributing developer method in the base box, primarily because it's the only method that doesn't require tying the installation to a specific user's Magento.com account, and to make the Magento 2 installation in MageScotch as flexible as possible so it can be used for many different purposes. One drawback to that, though, appears to be that in current versions of Magento 2.0, the web updater may not work 'out of the box' with MageScotch. Sorry about that!
