### ISSUE TITLE
Autoload error with Magento 2

### ISSUE THREAD

**Issue by lucabarbetti** [joshuaswarren/magescotch#6]
Hi Joshua,
my compliments and thank you for magescotch.
When I visit http://192.168.33.10/magento2/ I get an error:

```
Autoload error
Vendor autoload is not found. Please run 'composer install' under application root directory.
```

I run **composer install** under the root directory (public/magento2) as the message says (it installs a bunch of things and prints several messages that suggests installing several other things, which I have not done) and I restarted Vagrant with the command **vagrant reload** , but I still get the same error message.

On the contrary http://192.168.33.10/magento/ works well.

I use Vagrant 1.8.1 and VirtualBox 5.0.14 r105127 on Windows 10

Do you know how I could fix this problem?

Best regards,
Luca

[composer-install-output.txt](https://github.com/joshuaswarren/magescotch/files/157088/composer-install-output.txt)

**Comment by joshuaswarren** [comment]
Hello, Luca. Sorry I didn't get back to you on this sooner. I was curious - did you find a solution for this? I'm working on a number of improvements to MageScotch right now and I want to make sure that all of the common issues have better documentation.

**Comment by lucabarbetti** [comment]
Hi Joshua,
no problem, you have been and are doing a whole lot for all us!  
Actually no, I haven't found a solution yet, it seems that this problem goes a little bit over my head.
Thanks for your reply
