### ISSUE TITLE
Readme urls not working

### ISSUE THREAD

**Issue by nbennett25** [joshuaswarren/magescotch#8]
Hello - after a vanilla install, I'm getting 404s on both admin urls, the Project home url and the Magento 1 store url.

The only url from the README that is working properly is the Magento 2 store url.

**Comment by joshuaswarren** [comment]
I recently did a major redesign of how the files are laid out on MageScotch that probably caused this. What host operating system are you using, and was this from a recent (i.e., in the past week or so) fresh clone of the repo?

**Comment by nbennett25** [comment]
I'm on OS X, 10.10.5 - and I just cloned the master branch this morning.

**Comment by joshuaswarren** [comment]
Cool - my apologies for the difficulties. You're a bit of a beta user for
this new version. I'll try to get it fixed up this afternoon. I may have a
few commands for you to run to gather more troubleshooting info, I'll post
them here if I do.

On Mon, Apr 25, 2016 at 10:31 AM, nbennett25 notifications@github.com
wrote:

> I'm on OS X, 10.10.5 - and I just cloned the master branch this morning.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/joshuaswarren/magescotch/issues/8#issuecomment-214396969

## 

Joshua Warren, CEO, Creatuity Corp
creatuity.com | joshuawarren.com | @JoshuaSWarren
Magento Certified Developer Plus/Front-End Developer
Magento Certified Solution Specialist

**Comment by nbennett25** [comment]
Awesome - thanks joshuaswarren.

It's great to have a prebuilt Magento 2 vagrant box, thanks for all the effort. I'd actually like to build it out with PHP 7, but didn't see any config settings in the bootstrap.sh - is there a way to switch PHP versions?

Happy to help debug/tweek if it's helpful.

Thx

**Comment by joshuaswarren** [comment]
The PHP version is built into the basebox; it's on Github at
joshuaswarren/magemalt

The tricky part is - I've built MageScotch to be a bridge for devs working
on both M1 and M2. A lot of devs are still working on M1 sites that won't
work for various reasons under PHP 7, so I've kept it on PHP 5.

I've been wanting to do more with PHP 7 myself, so I'm trying to decide the
best way to offer an option for both. I'd rather not have 2 different
Vagrant setups to maintain though, so I'm still brainstorming on this one.

On Mon, Apr 25, 2016 at 11:12 AM, nbennett25 notifications@github.com
wrote:

> Awesome - thanks joshuaswarren.
> 
> It's great to have a prebuilt Magento 2 vagrant box, thanks for all the
> effort. I'd actually like to build it out with PHP 7, but didn't see any
> config settings in the bootstrap.sh - is there a way to switch PHP versions?
> 
> Happy to help debug/tweek if it's helpful.
> 
> Thx
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/joshuaswarren/magescotch/issues/8#issuecomment-214422155

## 

Joshua Warren, CEO, Creatuity Corp
creatuity.com | joshuawarren.com | @JoshuaSWarren
Magento Certified Developer Plus/Front-End Developer
Magento Certified Solution Specialist

**Comment by joshuaswarren** [comment]
This repository now contains the PHP 7 based version of MageScotch. I've moved the PHP 5 version to https://github.com/joshuaswarren/magescotch5

I've also confirmed the URLs in the Readme are now working fine.
